### ISSUE TITLE
Two 404 links in the magit-walk-through

### ISSUE THREAD

**Issue by duianto** [tarsius/emacsair.me#2]
There are two 404 links on the page:
https://emacsair.me/2017/09/01/magit-walk-through/

### In the `Applying changes` section
https://emacsair.me/2017/09/01/magit-walk-through/#applying-changes

In the second paragraphs, last sentence.

The link text: `consult` leads to the 404 page:
https://emacsair.me/manual/magit/Applying.html

The correct url might be:
https://magit.vc/manual/magit/Applying.html

This seems to be where it's defined:
https://github.com/tarsius/emacsair.me/blame/master/_posts/2017-09-01-magit-walk-through.md#L381

### In the `Arguments missing from popups` section
https://emacsair.me/2017/09/01/magit-walk-through/#arguments-missing-from-popups

In the first paragraphs last sentence. The link text: `described` leads to: 
https://emacsair.me/manual/magit-popup/Customizing-existing-popups.html

The correct url might be:
https://magit.vc/manual/magit-popup/Customizing-Existing-Popups.html

This seems to be where it's defined:
https://github.com/tarsius/emacsair.me/blame/master/_posts/2017-09-01-magit-walk-through.md#L387

### Working urls
The "correct" urls above seem to be right because the third url to a manual page.

In the `Fetching, pulling and pushing` section.
https://emacsair.me/2017/09/01/magit-walk-through/#fetching-pulling-and-pushing

The last word `this` leads to the working page: https://magit.vc/manual/magit/The-Two-Remotes.html

It seems to be defined here:
https://github.com/tarsius/emacsair.me/blame/master/_posts/2017-09-01-magit-walk-through.md#L562

All the other urls on the page works.

**Comment by tarsius** [comment]
Thanks for the report!

I have fixed these and a few other links in 513b4eec1f30b31e863f14e2ecb3c3b809e22f4e.
